#!/bin/bash

SESSION=$USER

# Create session
tmux -2 new-session -d -s $SESSION

tmux split-window -v
tmux split-window -h
tmux select-pane -t 1
tmux send-keys "htop" C-m
tmux split-window -h
tmux new-window -t $SESSION:0 -n 'Info'

tmux new-window -t $SESSION:1 -n 'Emacs'
tmux send-keys "emacs -nw" C-m

# Attach to session
tmux -2 attach-session -t $SESSION
