#!/usr/bin/zsh

SESSION=$USER

# Create session
tmux -2 new-session -d -s $SESSION

tmux new-window -t $SESSION:0 -n 'Info'
tmux split-window -v
tmux split-window -h
tmux select-pane -t 1
tmux send-keys "htop" C-m
tmux split-window -h

tmux new-window -t $SESSION:1 -n 'emacs'

tmux new-window -t $SESSION:2 -n 'cmd'
tmux split-window -h

tmux new-window -t $SESSION:3 -n 'vifm' 'vifm'

# Set default window
tmux select-window -t $SESSION:1
tmux select-pane -t 1
tmux send-keys "emacs -nw" C-m

# Attach to session
tmux -2 attach-session -t $SESSION
