#!/usr/bin/zsh

SESSION=$USER

tmux -2 new-session -d -s $SESSION

tmux split-window -v
tmux split-window -h
tmux select-pane -t 1
tmux send-keys "htop" C-m
tmux split-window -h

tmux new-window -t $SESSION:2 -n 'emacs'
tmux send-keys "emacs -nw" C-m
tmux new-window -t $SESSION:3 -n 'cmd'
tmux split-window -h
tmux new-window -t $SESSION:4 -n 'ranger' 'ranger'

# Set default window
tmux select-window -t $SESSION:2

tmux -2 attach-session -t $SESSION
