#!/bin/bash

DOTFILES_ROOT=$(pwd)

#symlink dotfiles into home directory
install_dotfiles () {

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find "$DOTFILES_ROOT/" -maxdepth 2 -name '*.symlink')
  do
    dst="$HOME/$(basename "${src%.*}")"
    ln -sf "$src" "$dst"
  done
}

install_dotfiles

#setup submodules of dotfiles
cd $DOTFILES_ROOT
git submodule init
git submodule sync
git submodule update

#setup oh-my-zsh
ln -sf $DOTFILES_ROOT/z/z.sh ~/z.sh
ln -sf $DOTFILES_ROOT/.oh-my-zsh ~/.oh-my-zsh
cd ~/.oh-my-zsh/custom/plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting

#setup pure theme for zsh
cd ~/.oh-my-zsh/custom/
git clone https://github.com/sindresorhus/pure
mv pure/pure.zsh pure.zsh-theme
mv pure/async.zsh async.zsh

#setup spacemacs
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
ln -sf $DOTFILES_ROOT/.spacemacs-config/snippets/* ~/.emacs.d/private/snippets

#setup submodules of spacemacs
cd ~/.emacs.d
git submodule init
git submodule sync
git submodule update
cd $DOTFILES_ROOT/.spacemacs-config/org-mode
make autoloads
