#!/bin/bash

DOTFILES_ROOT=$(pwd)

ln -sf $DOTFILES_ROOT/.spacemacs.d.symlink $HOME/.spacemacs.d
ln -sf $DOTFILES_ROOT/.zshenv.symlink $HOME/.zshenv
ln -sf $DOTFILES_ROOT/.zshrc.symlink $HOME/.zshrc
ln -sf $DOTFILES_ROOT/.tmux.conf.symlink $HOME/.tmux.conf
ln -sf $DOTFILES_ROOT/.mbsyncrc.symlink $HOME/.mbsyncrc
ln -sf $DOTFILES_ROOT/.Xdefaults.symlink $HOME/.Xdefaults
ln -sf $DOTFILES_ROOT/.latexmkrc.symlink $HOME/.latexmkrc
ln -sf $DOTFILES_ROOT/.Xresources.symlink $HOME/.Xresources
ln -sf $DOTFILES_ROOT/.p10k.zsh.symlink $HOME/.p10k.zsh
ln -sf $DOTFILES_ROOT/.config/* $HOME/.config
ln -sf $DOTFILES_ROOT/bin/* ~/bin
ln -sf $DOTFILES_ROOT/ranger/ranger.py ~/bin/ranger

touch $DOTFILES_ROOT/.spacemacs.d.symlink/custom.el

# setup submodules of dotfiles
cd $DOTFILES_ROOT
git submodule init
git submodule sync
git submodule update

# setup pyenv and submodules
ln -sf $DOTFILES_ROOT/.pyenv ~/.pyenv
cd $DOTFILES_ROOT/.pyenv
git submodule init
git submodule sync
git submodule update

# setup oh-my-zsh and submodules
cd $DOTFILES_ROOT
ln -sf $DOTFILES_ROOT/ohmyzsh ~/.oh-my-zsh
cd $DOTFILES_ROOT/ohmyzsh
git submodule init
git submodule sync
git submodule update

# setup spacemacs and submodules
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
ln -sf $DOTFILES_ROOT/.spacemacs.d.symlink/snippets/* ~/.emacs.d/private/snippets
cd ~/.emacs.d
git checkout develop
git submodule init
git submodule sync
git submodule update
