#!/bin/bash

DOTFILES_ROOT=$(pwd)

ln -sf $DOTFILES_ROOT/.spacemacs.d.symlink $HOME/.spacemacs.d
ln -sf $DOTFILES_ROOT/.zshenv.symlink $HOME/.zshenv
ln -sf $DOTFILES_ROOT/.zshrc.symlink $HOME/.zshrc
ln -sf $DOTFILES_ROOT/.tmux.conf.symlink $HOME/.tmux.conf
ln -sf $DOTFILES_ROOT/.Xdefaults.symlink $HOME/.Xdefaults
ln -sf $DOTFILES_ROOT/.latexmkrc.symlink $HOME/.latexmkrc
ln -sf $DOTFILES_ROOT/.latex_gitconfig.symlink $HOME/.latex_gitconfig
ln -sf $DOTFILES_ROOT/.config/* $HOME/.config
ln -sf $DOTFILES_ROOT/bin/* ~/bin
ln -sf $DOTFILES_ROOT/ranger/ranger.py ~/bin/ranger

touch $DOTFILES_ROOT/.spacemacs.d.symlink/custom.el

# setup submodules of dotfiles
cd $DOTFILES_ROOT
git submodule init
git submodule sync
git submodule update

# setup pyenv and submodules
ln -sf $DOTFILES_ROOT/.pyenv ~/.pyenv
cd $DOTFILES_ROOT/.pyenv
git submodule init
git submodule sync
git submodule update

# setup oh-my-zsh and submodules
cd $DOTFILES_ROOT
ln -sf $DOTFILES_ROOT/z/z.sh ~/z.sh
ln -sf $DOTFILES_ROOT/.oh-my-zsh ~/.oh-my-zsh
cd $DOTFILES_ROOT/.oh-my-zsh
git submodule init
git submodule sync
git submodule update

# setup pure theme for zsh
cd ~/.oh-my-zsh/custom/
git clone https://github.com/sindresorhus/pure
mv pure/pure.zsh pure.zsh-theme
mv pure/async.zsh async.zsh

# setup spacemacs and submodules
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
ln -sf $DOTFILES_ROOT/.spacemacs.d.symlink/snippets/* ~/.emacs.d/private/snippets
cd ~/.emacs.d
git submodule init
git submodule sync
git submodule update

# setup terminal theme
cd $DOTFILES_ROOT
bash terminal-theme.sh
