(defun my-python/send-region-compilation(start end)
  (interactive "r")
  (let ((cur-window (selected-window)))
    (append-to-buffer (get-buffer "*compilation*") start end)
    (switch-to-buffer-other-window (get-buffer "*compilation*"))
    (evil-insert-state)
    (execute-kbd-macro (read-kbd-macro "DEL"))
    (execute-kbd-macro (read-kbd-macro "RET"))
    (select-window cur-window)))

(defun my-python/send-region-compilation-dbg(start end)
  (interactive "r")
  (append-to-buffer (get-buffer "*compilation*") start end)
  (switch-to-buffer-other-window (get-buffer "*compilation*"))
  (evil-insert-state)
  (execute-kbd-macro (read-kbd-macro "DEL"))
  (execute-kbd-macro (read-kbd-macro "RET")))

(defun my-python/python-execute-file ()
  "Execute a python script in a shell."
  (interactive)
  (let ((cmd (format "%s %s"
                     (executable-find python-shell-interpreter)
                     (shell-quote-argument (file-name-nondirectory buffer-file-name)))))
    (compilation-start cmd nil (lambda (_) (generate-new-buffer-name "*compilation*")))))
